### PR TITLE
Gracefully handle invalid transaction flag values from server

### LINKED ISSUE #81: Flag color validation fails on some existing transactions fetched through the API
This might have been caused by a change in data format, combined with new validations added in recent versions of the gem.

I'm trying to fetch all transactions in a budget using the API:

```rb
ynab_api = YNAB::API.new(YNAB_ACCESS_TOKEN)
budget = ynab_api.budgets.get_budgets.data.budgets.find { _1.name == YNAB_BUDGET_NAME }
transactions = ynab_api.transactions.get_transactions(budget.id)
```

And I get the following error:
```
.../ynab-3.4.0/lib/ynab/models/transaction_flag_color.rb:39:in `build_from_hash': Invalid ENUM value  for class #TransactionFlagColor (RuntimeError)
        from .../ynab-3.4.0/lib/ynab/models/transaction_flag_color.rb:31:in `build_from_hash'
        from .../ynab-3.4.0/lib/ynab/models/transaction_detail.rb:431:in `_deserialize'
```
<details><summary>(continued...)</summary>

```
        from .../ynab-3.4.0/lib/ynab/models/transaction_detail.rb:386:in `block in build_from_hash'
        from .../ynab-3.4.0/lib/ynab/models/transaction_detail.rb:376:in `each_pair'
        from .../ynab-3.4.0/lib/ynab/models/transaction_detail.rb:376:in `build_from_hash'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response_data.rb:171:in `_deserialize'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response_data.rb:123:in `block (2 levels) in build_from_hash'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response_data.rb:123:in `map'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response_data.rb:123:in `block in build_from_hash'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response_data.rb:116:in `each_pair'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response_data.rb:116:in `build_from_hash'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response.rb:158:in `_deserialize'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response.rb:113:in `block in build_from_hash'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response.rb:103:in `each_pair'
        from .../ynab-3.4.0/lib/ynab/models/transactions_response.rb:103:in `build_from_hash'
        from .../ynab-3.4.0/lib/ynab/api_client.rb:282:in `convert_to_type'
        from .../ynab-3.4.0/lib/ynab/api_client.rb:242:in `deserialize'
        from .../ynab-3.4.0/lib/ynab/api_client.rb:73:in `call_api'
        from .../ynab-3.4.0/lib/ynab/api/transactions_api.rb:296:in `get_transactions_with_http_info'
        from .../ynab-3.4.0/lib/ynab/api/transactions_api.rb:240:in `get_transactions'
```

</details> 

I've also confirmed that the error started happening in the version 3.0.0 of the gem.

Hacking into the gem a little bit, I was able to find that my budget contains a transaction which flag is an empty string, when returned from the API, then I confirmed it by also querying the API directly:

```sh-session
$ curl --no-progress-meter -X 'GET' \
  'https://api.ynab.com/v1/budgets/0a08ffe7-0121-43c9-a9c6-7484e9138bd5/transactions/9aced28e-a240-47ff-b108-2d672872536c' \
  -H 'accept: application/json' \
  -H "Authorization: Bearer $YNAB_ACCESS_TOKEN" | \
jq '.data.transaction'
```
```json
{
  "id": "9aced28e-a240-47ff-b108-2d672872536c",
  "date": "2022-11-15",
  "flag_color": "", // 💥
  "flag_name": null,
  "account_id": "48d5416c-2351-49ab-ab4e-1d367b9756c7",
  "category_id": "98a88345-80e8-4015-9f4c-8b53858c84b3",
  // ...
}
```

A transaction with an empty string for flag color is invalid, according to the OpenAPI spec:

https://github.com/ynab/ynab-sdk-ruby/blob/825a49af31fa8bd10ee7406fc40bf72955a1b406/open_api_spec.yaml#L3276-L3287

I can picture three ways to fix this problem:

1. update the OpenAPI spec (and rebuild the gem), to mark the empty string as a valid value for `flag_color`
2. update the YNAB API server implementation to return null values when it meets an empty string from the database
3. run a migration on the YNAB user data to update all transactions with an invalid flag color

To me, the real fix would be number 3.

### PR DESCRIPTION
**Pull request by bradymholt**
The OpenAPI Generator, by default, throws an error if enum type data is received from the server that is not defined in the spec.  In theory, the spec should always match what the server returns but in some cases there are unexpected values (new enum values not introduced in client, old enum values no longer in use, etc., bugs).

To work around this, we'll gracefully handle unsupported values by converting them to `nil` in the client, rather than throwing an error.

Fixes #81

### CODE REVIEW

File: lib/ynab/models/account_type.rb [hunk 1]
```diff
@@ -41,8 +41,12 @@ def self.build_from_hash(value)
     # @param [String] The enum value in the form of the string
     # @return [String] The enum value
     def build_from_hash(value)
-      return value if AccountType.all_vars.include?(value)
-      raise "Invalid ENUM value #{value} for class #AccountType"
+      if AccountType.all_vars.include?(value)
+        return value
+      else
+        return nil
+      end
```
Comment (davidstosik) [inline lib/ynab/models/account_type.rb:48]: I'd expect these changes not to stick and a regression to happen as soon as the API Ruby code is regenerated from the OpenAPI spec file (for example using `rake generate`).

Is there a mechanism in place to prevent this kind of accidental regression to happen?

Note the comment at the top of most files:

https://github.com/ynab/ynab-sdk-ruby/blob/f3266625a91cc98dbcf6ecaf86af25b0630e4164/lib/ynab/models/account_type.rb#L6

**Review by davidstosik — COMMENTED** [review]
Thank you for taking a look at this! ❤️ 
~~Just not sure this approach would stick, long-term. 🤔~~

File: lib/ynab/models/account_type.rb (hunk 1 above)
Comment (bradymholt) [reply lib/ynab/models/account_type.rb:48]: Yes - that template should ensure the changes stay intact on next generation.
